[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"


[project]
name = "sudoku-toolkit"
version = "0.1.0"
description = "A Python library for solving and generating Sudoku puzzles."
requires-python = ">=3.10"
authors = [
    {name = "Leonard Hell"}
]

[project.optional-dependencies]
test = [
    "pytest>=7",
    "pytest-cov>=4",
]

[project.scripts]
sudoku = "sudoku_toolkit.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
